import '../../models/transactions/transactions.dart';

final USER_TRANSACTIONS = [
  Transactions(
    id: "c1",
    category: "transport",
    fromStation: "Høje Taastrup",
    toStation: "København H",
    date: DateTime.utc(2022, 7, 7, 17, 00),
    amount: 32.0,
  ),
  Transactions(
    id: "c2",
    category: "transport",
    fromStation: "København H",
    toStation: "Høje Taastrup",
    date: DateTime.utc(2022, 7, 7, 17, 30),
    amount: 40.0,
  ),
  Transactions(
    id: "c3",
    category: "transport",
    fromStation: "Valby",
    toStation: "Danshøj",
    date: DateTime.utc(2022, 7, 9, 16, 56),
    amount: 20.0,
  ),
  Transactions(
    id: "c4",
    category: "transport",
    fromStation: "Danshøj",
    toStation: "Valby",
    date: DateTime.utc(2022, 7, 9, 17, 27),
    amount: 20.0,
  ),
  Transactions(
    id: "c5",
    category: "transport",
    fromStation: "Høje Taastrup",
    toStation: "København H",
    date: DateTime.utc(2022, 7, 12, 12, 22),
    amount: 32.0,
  ),
  Transactions(
    id: "c6",
    category: "transport",
    fromStation: "København H",
    toStation: "Høje Taastrup",
    date: DateTime.utc(2022, 7, 12, 12, 56),
    amount: 40.0,
  ),
  Transactions(
    id: "c7",
    category: "transport",
    fromStation: "Valby",
    toStation: "Danshøj",
    date: DateTime.utc(2022, 7, 15, 19, 10),
    amount: 20.0,
  ),
  Transactions(
    id: "c8",
    category: "transport",
    fromStation: "Danshøj",
    toStation: "Valby",
    date: DateTime.utc(2022, 7, 15, 19, 27),
    amount: 20.0,
  ),
  Transactions(
    id: "c9",
    category: "refuel",
    date: DateTime.utc(2022, 7, 16, 22, 58),
    amount: 20.0,
  ),
];
